# Generated by Django 4.0.2 on 2022-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='ordering/images'),
        ),
    ]
