# Generated by Django 4.0.2 on 2022-03-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0014_remove_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
