# Generated by Django 4.0.2 on 2022-03-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0015_order_order_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together=set(),
        ),
    ]
