# Generated by Django 4.0.2 on 2022-03-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0016_alter_orderline_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.IntegerField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
