# Generated by Django 4.0.2 on 2022-03-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0023_remove_order_address_remove_orderitem_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpaypaymentid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
